FROM node:lts AS builder

WORKDIR /app

COPY /webui/package*.json ./
RUN npm i

COPY /webui/ ./
RUN npm run build-prod

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
